version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "04:00"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  groups:
    rubocop:
      patterns:
        - "rubocop*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  groups:
    babel:
      patterns:
        - "@babel/*"
    fontawesome:
      patterns:
        - "@fortawesome/*"
    rails:
      patterns:
        - "@rails/*"
    webpack:
      patterns:
        - "webpack*"
