name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: "${{ github.workflow }} / rubocop @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          .github/workflows/lint.yml
          .rubocop.yml
          **.rb
          **.rake
          Gemfile*
          Rakefile
    - name: Set up Ruby
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Run RuboCop
      if: steps.changed-files.outputs.any_changed == 'true'
      run: bundle exec rubocop --format github

  i18n:
    name: I18n tasks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: "${{ github.workflow }} / i18n @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          .github/workflows/lint.yml
          config/i18n-tasks.yml
          config/locales/**/*.yml
          app/**/*
          Gemfile*
    - name: Setup Ruby
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Run i18n-tasks health
      if: steps.changed-files.outputs.any_changed == 'true'
      run: bundle exec i18n-tasks health

  slimlint:
    name: Slim-Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: "${{ github.workflow }} / slimlint @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          .github/workflows/lint.yml
          .slim-lint.yml
          **.slim
    - name: Set up Ruby
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Run Slim-Lint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: bundle exec slim-lint . -r github

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: "${{ github.workflow }} / eslint @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          .eslintignore
          .eslintrc.cjs
          .github/workflows/lint.yml
          app/**/*.js
    - uses: pnpm/action-setup@v4
    - name: Set up Node
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - name: Install node dependencies
      run: pnpm install
    - name: Run ESLint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: pnpm eslint app/**/*.js

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: "${{ github.workflow }} / stylelint @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          .github/workflows/lint.yml
          .stylelintrc
          app/**/*.{scss,css}
    - uses: pnpm/action-setup@v4
    - name: Set up Node
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - name: Install node dependencies
      run: pnpm install
    - name: Install stylelint GitHub formatter
      run: pnpm install @csstools/stylelint-formatter-github
    - name: Run Stylelint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: pnpm stylelint app/**/*.{scss,css} --custom-formatter @csstools/stylelint-formatter-github
